apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image:  adityakumar2809/complex-fibonacci-worker
      ports:
        - containerPort: 3000